# Generated by Django 2.2.5 on 2019-11-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('foto', models.FileField(blank=True, null=True, upload_to='banner')),
            ],
            options={
                'db_table': 'banner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CidadesPorEtado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj_cpf', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.ForeignKey(on_delete='SET_NULL', to='E_contas.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj_cpf', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('tipo_de_parceria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LocalPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('adm_cartao', models.CharField(max_length=255)),
                ('bandeira_cartao', models.CharField(max_length=255)),
                ('modo_pagamento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusDoPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('parcelas', models.IntegerField()),
                ('data', models.DateField(max_length=255)),
                ('local_de_pagamento', models.ForeignKey(on_delete='SET_NULL', to='E_contas.LocalPagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('data_de_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('parcela', models.CharField(blank=True, max_length=255, null=True)),
                ('competencia', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_juros', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('data_de_pagamento', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete='SEL_NULL', to='E_contas.Empresa')),
                ('fornecedor', models.ForeignKey(blank=True, on_delete='SET_NULL', to='E_contas.Fornecedor')),
                ('status_pagamento', models.ForeignKey(on_delete='SET_NULL', to='E_contas.StatusDoPagamento')),
                ('tipo_de_pagamento', models.ForeignKey(on_delete='SET_NULL', to='E_contas.TipoPagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=1000)),
                ('data_evento', models.DateField(max_length=255)),
                ('hora_evento', models.DateField()),
                ('realizado', models.BooleanField(default=False)),
                ('categoria_evento', models.ForeignKey(on_delete='SET_NULL', to='E_contas.CategoriaEvento')),
                ('endereco', models.ForeignKey(on_delete='SET_NULL', to='E_contas.Endereco')),
            ],
        ),
        migrations.AddField(
            model_name='endereco',
            name='estado',
            field=models.ForeignKey(on_delete='SET_NULL', to='E_contas.Estado'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete='SET_NULL', to='E_contas.Estado'),
        ),
    ]
