# Generated by Django 2.2.5 on 2019-12-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_contas', '0002_auto_20191204_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='local_de_pagamento',
        ),
        migrations.AddField(
            model_name='venda',
            name='local_de_recebimento',
            field=models.ForeignKey(default=1, on_delete='SET_NULL', to='E_contas.LocalRecebimento'),
            preserve_default=False,
        ),
    ]
